# Generated by Django 5.2.8 on 2025-12-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auditlog'),
        ('posts', '0003_groupmembership_role'),
    ]

    operations = [
    ]
